Convert a 1D array to a 2D array with 2 rows.

In [6]:
import numpy as np
arr = np.arange(10) 
print(arr.shape)
reshape = arr.reshape(2,-1)
reshape.shape


(10,)


(2, 5)

In [ ]:
#arrange(num)
#reshape(x,y # x,y multiple of num)

Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [12]:
zero_array = np.zeros(10)

ones_array = np.ones(10)

fives_array = np.full((10,),5)

print(fives_array)


[5 5 5 5 5 5 5 5 5 5]


Write a NumPy program to create an array of the integers from 30 to 70.

In [17]:
range_array = np.arange(30,70)
range_array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [25]:
ndist_array = np.random.normal(0,1,(15))
ndist_array

array([-0.61638293, -0.79507898, -0.63814518, -2.45453942, -1.07701549,
        2.03152249,  0.77710348,  0.79920767, -1.21327689,  0.32163655,
        0.63020017, -0.40173559, -1.03112697, -2.08116216, -0.77021168])

Write a NumPy program to create an array of all the even integers from 30 to 70.

In [28]:
#third parameter is used to check the condition and prints the result if condition satisfied
#here it checks if the number is divisible by 2
even_range_array = np.arange(30,71,2)
even_range_array

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [34]:
matrix = np.arange(2,11).reshape(3,3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

<li> Create a 3x5 random matrix using normal distribution with mean = 2 and std = .5 (matrix A)</li>
<li> Create another 5x3 matrix in the following format: (matrix B) 
<br>
<br>
<div>
<table style="width:200px; border:1px solid black">
<tr>
    <td style="text-align:center; border:1px solid black">1</td>
    <td style="text-align:center; border:1px solid black">0</td>
    <td style="text-align:center; border:1px solid black">2</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">3</td>
    <td style="text-align:center;border:1px solid black">4</td>
    <td style="text-align:center;border:1px solid black">1</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">-1</td>
    <td style="text-align:center; border:1px solid black">2</td>
    <td style="text-align:center;border:1px solid black">-3</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">5</td>
    <td style="text-align:center; border:1px solid black">4</td>
    <td style="text-align:center; border:1px solid black">0</td>
</tr>
<tr>
    <td style="text-align:center;border:1px solid black">0</td>
    <td style="text-align:center;border:1px solid black">0</td>
    <td style="text-align:center;border:1px solid black">2</td>
</tr>
</table>
<div></li>
   
<li> Find Dot Product of matrix A and B and put it in matrix C.</li>
<li> Find the column wise sum of the matrix C.</li> 
</p>


In [39]:

matrixA = np.random.normal(2,0.5,(3,5))
matrixA

array([[2.2655319 , 2.40594045, 1.97660718, 1.75761843, 2.63265959],
       [2.80692868, 2.40587742, 2.01755007, 1.6864253 , 2.51980334],
       [1.84920438, 1.66950246, 2.00599903, 1.57906501, 2.17321446]])

In [40]:
matrixB = np.array([[1,0,2],[3,4,1],[-1,2,-3],[5,4,0],[0,0,2]])
matrixB

array([[ 1,  0,  2],
       [ 3,  4,  1],
       [-1,  2, -3],
       [ 5,  4,  0],
       [ 0,  0,  2]])

In [45]:
matrixC = matrixA.dot(matrixB)

In [47]:
matrixC.sum(axis = 0)

array([45.48101336, 58.01802881, 16.97553619])

<li>Create a random 5x5 matrix using discrete uniform integers between [0, 100) (matrix A) </li>
    <li>Use Boolean Indexing (Filtering) to subtract 15 from all the values over 60 in matrix A </li>

In [50]:
uniform_matrix = np.random.uniform(0,100,(5,5))
uniform_matrix

array([[ 4.13416815, 67.95695762, 97.2022678 , 34.70581307, 21.19359906],
       [35.49231731, 26.55596882, 18.66400858, 15.76419963, 75.80300649],
       [79.88851249, 78.70952267,  2.97691225, 84.19047667, 40.00963437],
       [84.5232098 , 79.81306562, 83.0335251 , 40.49486965, 61.85726076],
       [34.95770762, 64.48511306, 85.67932848,  9.27509401, 92.13470743]])

In [53]:
filter = uniform_matrix > 60

uniform_matrix[filter] -= 15
uniform_matrix

array([[ 4.13416815, 52.95695762, 67.2022678 , 34.70581307, 21.19359906],
       [35.49231731, 26.55596882, 18.66400858, 15.76419963, 45.80300649],
       [49.88851249, 48.70952267,  2.97691225, 54.19047667, 40.00963437],
       [54.5232098 , 49.81306562, 53.0335251 , 40.49486965, 46.85726076],
       [34.95770762, 49.48511306, 55.67932848,  9.27509401, 62.13470743]])

* arange
* reshape
* normal and uniform distribution
* array creation with desired dimensions
* filtering in array 
* dot product
* sorting
* argsort()

